#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=01:00:00,vmem=8gb

mkdir -p output

cfa=`jq -r '.peaks' config.json`
fa_template=`jq -r '.fa_template' config.json`

if [ $fa_template == 'FMRIB58_FA_1mm' ]; then 
	template=FMRIB58_FA_1mm.nii.gz
elif [ $fa_template == 'IITmean_FA' ]; then 
	template=IITmean_FA.nii.gz
fi 

echo "ANTs registration"
singularity exec -e docker://brainlife/ants:2.2.0 ./run_mni_registration.sh $cfa $template

if [ -f 'output/peaks.nii.gz' ]; then 
    echo "Colored FA registered to the template."
else 
    echo "Failed."
    exit 1
fi
